### ISSUE TITLE
Missing type definitions for `@keyframes`

### ISSUE THREAD

**Issue by OliverJAsh** [mizdra/css-modules-kit#191]
👋 Hey! Should CMK output type definitions for `@keyframes`? It looks like it currently doesn't. For context, we're migrating from `typed-css-modules` which does support this.

```css
@keyframes fadeIn {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}

```
